services:
  mongodb:
    image: "mongo"
    volumes:
      - database:/data/db
    env_file:
      - ./backend/.env.production
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    volumes:
      - public_uploads:/home/public/uploads
    env_file:
      - ./backend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  database:
  public_uploads:
